server:
  port: 7001
  servlet:
    context-path: '/ProductService'
application:
 discriptive-name: 'ProductService'
 describtion: 'Information about products'
 version: '1.0.0'
 

logging:
   level:
     com.hm.product.services : DEBUG
     org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true


---

spring:
  profiles: docker
server:
  port: 80

spring.data.mongodb.host: mongodb

---
spring.profiles: prod

spring.data.mongodb.host: 172.17.0.1

logging:
  level:
    root: WARN
    se.magnus: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN



