server:
  port: 7003
  servlet:
    context-path: '/RecommedationService'
application:
    discriptive-name: 'RecommedationService'
    describtion: 'RecommedationService suggeste recommndation service'
    version: '1.0.0'  

logging:
   level:
     com.hm.recommedation: DEBUG
     org.springframework.data.mongodb.core.MongoTemplate: INFO
     reactor.netty.http.client logging: INFO
     
spring.application.name: recommendation    

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  
       
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: recommendations
    group: recommendationsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

---

spring:
  profiles: docker
server:
  port: 80

spring.data.mongodb.host: mongodb
---
spring.profiles: prod
spring.rabbitmq.host: 172.17.0.1
spring.data.mongodb.host: 172.17.0.1

logging:
  level:
    root: WARN
    se.magnus: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN
   

