server:
  error:
    include-message: always
    include-stacktrace: always 
  port: 7004
  servlet:
    context-path: '/ReviewService'
    
spring.jpa.hibernate.ddl-auto: update


spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd
  
spring.datasource.hikari.initializationFailTimeout: 60000  
    
application:
    discriptive-name: 'ReviewService'
    describtion: 'ReviewService shows all the reviwes related to a product'
    version: '1.0.0'
    
logging:
   level:
     org.hibernate.SQL: INFO
     org.hibernate.type.descriptor.sql.BasicBinder: INFO
     
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: reviews
    group: reviewsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true
  
---

spring:
  profiles: docker
server:
  port: 80   
  
spring.datasource:
  url: jdbc:mysql://mysql/review-db 

